argo-cd:
  crds:
    # By default, CRDs are left behind on uninstall.
    # Uninstall them (deleting everything!) instead.
    keep: false

  configs:
    params:
      server.insecure: true # prevent http->https redirect for ingress that goes to http
    cm:
      resource.customizations: |
        # HAProxy doesn't annotate Ingress with status, we'll assume healthy
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs

