apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applicationset
spec:
  generators:
  - scmProvider:
      github:
        organization: klodnicki-cluster
      filters:
      - pathsExist:
        - Chart.yaml
  template:
    metadata:
      name: {{ "{{ repository }}" | quote }}
    spec:
      project: default
      source:
        repoURL: {{ "{{ url }}" | quote }}
        targetRevision: {{ "{{ branch }}" | quote }}
        path: '/'
      destination:
        name: in-cluster
        namespace: {{ "{{ cluster }}" | quote }}
   