apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applicationset
spec:
  generators:
  - scmProvider:
      cloneProtocol: https
      github:
        organization: klodnicki-cluster
        tokenRef:
          secretName: access-token-github-klodnicki
          key: accessToken
      filters:
      - pathsExist:
        - Chart.yaml
  template:
    metadata:
      name: {{ "{{ repository }}" | quote }}
    spec:
      project: default
      source:
        repoURL: {{ "{{ url }}" | quote }}
        targetRevision: {{ "{{ branch }}" | quote }}
        path: '.'
      destination:
        name: in-cluster
        namespace: {{ "{{ repository }}" | quote }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
